# Generated by Django 5.1.3 on 2024-11-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
