# Generated by Django 5.1.3 on 2024-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refApp', '0002_alter_user_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referrals',
            field=models.CharField(default=''),
        ),
    ]
